name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt

    - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf .
          cp -r $GITHUB_WORKSPACE/build/* .
          git add -A
          git commit -m "Auto-publish to GitHub Pages"
          git push origin gh-pages
